@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM ==========================================
REM  LMS Interactive Setup Wizard
REM  Single Click - Prompts for Credentials
REM ==========================================

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

cls
echo.
echo ╔════════════════════════════════════════════════════════════╗
echo ║                                                            ║
echo ║      📚 LMS Setup Wizard - Interactive Mode 📚            ║
echo ║                                                            ║
echo ╚════════════════════════════════════════════════════════════╝
echo.

REM ==========================================
REM  Step 1: Check Requirements
REM ==========================================

echo ═ Step 1/4: Checking Requirements
echo.

where java >nul 2>nul
if errorlevel 1 (
    echo ✗ Java is not installed
    echo   Please install Java 8 or higher and try again.
    echo   Download from: https://www.oracle.com/java/technologies/downloads/
    pause
    exit /b 1
)

for /f "tokens=3" %%v in ('java -version 2^>^&1 ^| findstr /i "version"') do (
    set JAVA_VERSION=%%v
    goto :java_found
)
:java_found
set JAVA_VERSION=%JAVA_VERSION:"=%
echo ✓ Java found: %JAVA_VERSION%
echo.

REM ==========================================
REM  Step 2: Get Oracle Credentials
REM ==========================================

echo ═ Step 2/4: Oracle Database Configuration
echo.
echo Please provide your Oracle database connection details:
echo.

REM Database URL with default
set "DB_URL=jdbc:oracle:thin:@localhost:1521:xe"
set /p DB_URL="→ Oracle database URL [%DB_URL%]: "
echo.

REM System username with default
set "SYS_USER=system"
set /p SYS_USER="→ Oracle SYSTEM username [%SYS_USER%]: "
echo.

REM System password (hidden input - Windows doesn't support this natively)
REM We'll prompt the user to type it
set /p SYS_PASSWORD="→ Oracle SYSTEM password [oracle]: "
if "%SYS_PASSWORD%"=="" (
    set "SYS_PASSWORD=oracle"
)
echo.

echo ✓ Database credentials configured
echo.

REM ==========================================
REM  Step 3: Create .env.setup
REM ==========================================

echo ═ Step 3/4: Creating Configuration File
echo.

(
    echo # LMS Setup Configuration
    echo # Generated by interactive setup wizard
    echo.
    echo LMS_DB_URL=%DB_URL%
    echo LMS_SYSTEM_USER=%SYS_USER%
    echo LMS_SYSTEM_PASSWORD=%SYS_PASSWORD%
    echo LMS_DB_USER=PRJ2531H
    echo LMS_DB_PASSWORD=PRJ2531H
) > "%SCRIPT_DIR%\.env.setup"

echo ✓ Configuration file created: .env.setup
echo.

REM ==========================================
REM  Step 4: Compile and Run Setup Wizard
REM ==========================================

echo ═ Step 4/4: Starting Setup Wizard
echo.

cd /d "%SCRIPT_DIR%"

REM Create bin directory if it doesn't exist
if not exist bin (
    echo → Creating bin directory...
    mkdir bin
)

REM Compile setup wizard classes
echo → Compiling setup wizard...

javac -d bin --release 8 -cp "bin;lib\*" ^
    src\com\library\setup\LMSSetupWizard.java ^
    src\com\library\setup\InstallationManager.java ^
    src\com\library\database\DBConnection.java ^
    src\com\library\service\PasswordHasher.java 2>nul

if errorlevel 1 (
    echo ✗ Compilation failed
    pause
    exit /b 1
)

echo ✓ Compilation successful
echo.
echo Starting Setup Wizard...
echo.

REM ==========================================
REM  Run Setup Wizard with Environment
REM ==========================================

REM Set environment variables for Java
set "LMS_DB_URL=%DB_URL%"
set "LMS_SYSTEM_USER=%SYS_USER%"
set "LMS_SYSTEM_PASSWORD=%SYS_PASSWORD%"

REM Run the setup wizard
java -Doracle.jdbc.timezoneAsRegion=false -jar LMS-Setup.jar

set EXIT_CODE=%ERRORLEVEL%

echo.
if %EXIT_CODE% equ 0 (
    echo ✓ Setup completed successfully!
    echo.
    echo Your LMS installation is ready. Next steps:
    echo   1. Run: run.bat
    echo   2. Access the application
    echo.
) else (
    echo ✗ Setup failed with exit code: %EXIT_CODE%
    echo.
    echo Troubleshooting:
    echo   • Check that Oracle is running on %DB_URL%
    echo   • Verify the SYSTEM user credentials are correct
    echo   • Check .env.setup for any issues
    echo.
)

REM Optional: Delete .env.setup after setup (uncomment if you want)
REM del "%SCRIPT_DIR%\.env.setup"

pause
exit /b %EXIT_CODE%
