#!/bin/bash

# LMS Interactive Setup Wizard - Single Click Setup
# Prompts user for Oracle credentials before running setup

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

show_header() {
    clear
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                                                            ║${NC}"
    echo -e "${GREEN}║          📚 LMS Setup Wizard - Interactive Mode 📚          ║${NC}"
    echo -e "${GREEN}║                                                            ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

show_header

echo -e "${YELLOW}This wizard will guide you through the LMS setup process.${NC}"
echo -e "${YELLOW}It will ask for your Oracle database credentials.${NC}"
echo ""

# Step 1: Check Java
echo -e "${BLUE}═ Step 1/4: Checking Requirements${NC}"
echo ""

if ! command -v java &> /dev/null; then
    echo -e "${RED}✗ Error: Java is not installed${NC}"
    echo "Please install Java 8 or higher and try again."
    exit 1
fi

JAVA_VERSION=$(java -version 2>&1 | grep -oP '(?<=version ")[^"]*' || echo "unknown")
echo -e "${GREEN}✓ Java found: $JAVA_VERSION${NC}"
echo ""

# Step 2: Get Oracle Credentials
echo -e "${BLUE}═ Step 2/4: Oracle Database Configuration${NC}"
echo ""
echo -e "${YELLOW}Please provide your Oracle database connection details:${NC}"
echo ""

read -p "$(echo -e ${BLUE}→${NC}) Oracle database URL [jdbc:oracle:thin:@localhost:1521:xe]: " DB_URL
if [ -z "$DB_URL" ]; then
    DB_URL="jdbc:oracle:thin:@localhost:1521:xe"
fi
echo ""

read -p "$(echo -e ${BLUE}→${NC}) Oracle SYSTEM username [system]: " SYS_USER
if [ -z "$SYS_USER" ]; then
    SYS_USER="system"
fi
echo ""

read -sp "$(echo -e ${BLUE}→${NC}) Oracle SYSTEM password [oracle]: " SYS_PASSWORD
if [ -z "$SYS_PASSWORD" ]; then
    SYS_PASSWORD="oracle"
fi
echo ""
echo ""

echo -e "${GREEN}✓ Database credentials configured${NC}"
echo ""

# Step 3: Create .env.setup
echo -e "${BLUE}═ Step 3/4: Creating Configuration File${NC}"
echo ""

cat > .env.setup << ENVEOF
# LMS Setup Configuration
# Generated by interactive setup wizard

LMS_DB_URL=$DB_URL
LMS_SYSTEM_USER=$SYS_USER
LMS_SYSTEM_PASSWORD=$SYS_PASSWORD
LMS_DB_USER=PRJ2531H
LMS_DB_PASSWORD=PRJ2531H
ENVEOF

echo -e "${GREEN}✓ Configuration file created: .env.setup${NC}"
echo ""

# Step 4: Compile and Run Setup Wizard
echo -e "${BLUE}═ Step 4/4: Starting Setup Wizard${NC}"
echo ""

if [ ! -d "bin" ]; then
    echo -e "${YELLOW}→ Creating bin directory...${NC}"
    mkdir -p bin
fi

echo -e "${YELLOW}→ Compiling setup wizard...${NC}"
if javac -d bin --release 8 -cp "bin:lib/*" \
    src/com/library/setup/LMSSetupWizard.java \
    src/com/library/setup/InstallationManager.java \
    src/com/library/database/DBConnection.java \
    2>/dev/null; then
    echo -e "${GREEN}✓ Compilation successful${NC}"
else
    echo -e "${RED}✗ Compilation failed${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Starting Setup Wizard...${NC}"
echo ""

export LMS_DB_URL
export LMS_SYSTEM_USER
export LMS_SYSTEM_PASSWORD

java -Doracle.jdbc.timezoneAsRegion=false \
  -cp "bin:lib/*" \
  com.library.setup.LMSSetupWizard

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo ""
    echo -e "${GREEN}✓ Setup completed successfully!${NC}"
    echo ""
    echo -e "${YELLOW}Your LMS installation is ready. Next steps:${NC}"
    echo "  1. Run: ./run.sh"
    echo "  2. Access the application"
    echo ""
else
    echo ""
    echo -e "${RED}✗ Setup failed with exit code: $EXIT_CODE${NC}"
    echo ""
    echo -e "${YELLOW}Troubleshooting:${NC}"
    echo "  • Check that Oracle is running on $DB_URL"
    echo "  • Verify the SYSTEM user credentials are correct"
    echo "  • Check .env.setup for any issues"
    echo ""
fi

exit $EXIT_CODE
