-- CREATE USER AND GRANT PRIVILEGES


DROP USER PRJ2531H CASCADE;
CREATE USER PRJ2531H IDENTIFIED BY PRJ2531H;
GRANT CONNECT, RESOURCE TO PRJ2531H;
GRANT DBA TO PRJ2531H;
GRANT UNLIMITED TABLESPACE TO PRJ2531H;
CONNECT PRJ2531H/PRJ2531H;

--LOGIN MODULE

-- CREDENTIAL TABLE WHERE THE LOGIN CREDENTIALS OF THE USERS ARE STORED. THIS TABLE IS USED FOR AUTHENTICATION PURPOSES.

CREATE TABLE TBL_CREDENTIALS (
    USER_ID   CHAR(5) CONSTRAINT LOGIN_PK PRIMARY KEY, -- USER ID FOR LOGIN
    NAME      VARCHAR2(20) NOT NULL, -- NAME OF THE USER
    PSWD	VARCHAR2(10) NOT NULL, -- PASSWORD FOR LOGIN
    EMAIL     VARCHAR2(20) NOT NULL,    -- EMAIL OF THE USER
    PHNO      NUMBER(10) NOT NULL -- PHONE NUMBER OF THE USER
);

--BOOK MODULE

-- BOOK INFORMATION TABLE WHERE THE DETAILS OF THE BOOKS ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE BOOKS AVAILABLE IN THE LIBRARY.

CREATE TABLE TBL_BOOK_INFORMATION (
    ACCESS_NO   CHAR(4) CONSTRAINT BK_INFO_PK PRIMARY KEY, -- ACCESSION NUMBER OF THE BOOK
    AUTHOR_NAME VARCHAR2(50) NOT NULL, -- AUTHOR NAME OF THE BOOK
    BK_TITLE    VARCHAR2(100) NOT NULL, -- TITLE OF THE BOOK
    VOLUME      NUMBER(2), -- VOLUME OF THE BOOK
    EDITION	NUMBER(2) NOT NULL, -- EDITION OF THE BOOK
    PUBLISHER	VARCHAR(20) NOT NULL, -- PUBLISHER OF THE BOOK
    PUB_YEAR    NUMBER(4) NOT NULL, -- PUBLICATION YEAR OF THE BOOK
    PAGES       NUMBER(5) NOT NULL, -- NUMBER OF PAGES IN THE BOOK
    SOURCE      VARCHAR2(10) NOT NULL, -- SOURCE OF THE BOOK (PURCHASED/DONATED)
    CLASS_NO	CHAR(6), -- CLASSIFICATION NUMBER OF THE BOOK
    U_PRICE     NUMBER(6,2) NOT NULL, -- UNIT PRICE OF THE BOOK
    B_NO        CHAR(3), -- BILL NUMBER OF THE BOOK
    B_DATE      DATE, -- BILL DATE OF THE BOOK
    WITHDRAWN	DATE, -- WITHDRAWN DATE OF THE BOOK
    REMARKS     VARCHAR2(50), -- REMARKS ABOUT THE BOOK
);

-- BOOK STOCK TABLE WHERE THE DETAILS OF THE BOOK STOCK ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE BOOK STOCK AVAILABLE IN THE LIBRARY.

CREATE TABLE TBL_BOOK_STOCK (

    BK_TITLE    VARCHAR2(100), -- TITLE OF THE BOOK
    BK_AUTHOR	VARCHAR2(20), -- AUTHOR OF THE BOOK
    BK_EDITION  NUMBER(2), -- EDITION OF THE BOOK
    P_LOCATION  VARCHAR2(50) NOT NULL, -- PHYSICAL LOCATION OF THE BOOK IN THE LIBRARY
    QUANTITY    NUMBER(3) NOT NULL, -- QUANTITY OF THE BOOK IN THE STOCK
    AVAIL_QTY	NUMBER(3) NOT NULL, -- AVAILABLE QUANTITY OF THE BOOK IN THE STOCK

    CONSTRAINT FK_STOCK_BOOK FOREIGN KEY (BK_TITLE) REFERENCES TBL_BOOK_INFORMATION (BK_TITLE)  -- FOREIGN KEY CONSTRAINT ON BOOK TITLE
);


--STUDENT MODULE

-- STUDENT TABLE WHERE THE DETAILS OF THE STUDENTS ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE STUDENTS WHO ARE MEMBERS OF THE LIBRARY.

CREATE TABLE TBL_STUDENT (
    CARD_ID   CHAR(9) CONSTRAINT STUD_PK PRIMARY KEY, -- LIBRARY CARD ID OF THE STUDENT
    ROLL      NUMBER(5) NOT NULL UNIQUE, -- ROLL NUMBER OF THE STUDENT
    NAME      VARCHAR2(50) NOT NULL, -- NAME OF THE STUDENT
    PH_NO     NUMBER(10) NOT NULL, -- PHONE NUMBER OF THE STUDENT  
    ADDR      VARCHAR2(100) NOT NULL, -- ADDRESS OF THE STUDENT
    COURSE    CHAR(3) NOT NULL, -- COURSE OF THE STUDENT
    ACAD_SESSION   CHAR(9) NOT NULL, -- ACADEMIC SESSION OF THE STUDENT
    RECEIPT_NO VARCHAR(10) NOT NULL UNIQUE, -- RECEIPT NUMBER OF THE STUDENT
    ISSUED_BY VARCHAR2(20) NOT NULL, -- NAME OF THE LIBRARIAN WHO ISSUED THE LIBRARY CARD TO THE STUDENT
    ISSUE_DATE DATE DEFAULT SYSDATE NOT NULL, -- ISSUE DATE OF THE LIBRARY CARD
    BOOK_LIMIT NUMBER(1) DEFAULT 1 NOT NULL, -- MAXIMUM NUMBER OF BOOKS THAT THE STUDENT CAN ISSUE
    FEE  NUMBER(5,2) NOT NULL, -- FEE OF THE STUDENT
    STATUS VARCHAR2(9) NOT NULL -- STATUS OF THE STUDENT (ACTIVE/INACTIVE)
);


--TRANSACTIONS MODULE

-- SELLER TABLE WHERE THE DETAILS OF THE SELLERS ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE SELLERS WHO SUPPLY BOOKS TO THE LIBRARY.

CREATE TABLE TBL_SELLER (
    S_ID       CHAR(10) CONSTRAINT SEL_PK PRIMARY KEY, -- SELLER ID FOR LOGIN
    COMP_NAME  VARCHAR2(30) NOT NULL,-- COMPANY NAME OF THE SELLER
    S_PH_NUMB  NUMBER(10) NOT NULL,-- PHONE NUMBER OF THE SELLER
    S_EMAIL    VARCHAR2(50) NOT NULL,-- EMAIL OF THE SELLER
    CONT_PRSN  VARCHAR2(30), -- CONTACT PERSON OF THE SELLER
    PH_NUMB    NUMBER (10) NOT NULL,   -- PHONE NUMBER OF THE CONTACT PERSON
    EMAIL      VARCHAR2(50), -- EMAIL OF THE CONTACT PERSON
    ADDR       VARCHAR2(100) NOT NULL -- ADDRESS OF THE SELLER
);

-- BOOK ORDER TABLE WHERE THE DETAILS OF THE BOOK ORDERS ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE BOOK ORDERS PLACED BY THE LIBRARY TO THE SELLERS.

CREATE TABLE TBL_BOOK_ORDER (
    ORD_ID        CHAR(10), -- ORDER ID OF THE BOOK
    BK_TTL        VARCHAR2(100) NOT NULL, -- TITLE OF THE BOOK
    AUTHOR        VARCHAR2(100) NOT NULL, -- AUTHOR OF THE BOOK
    PUBLICATION   VARCHAR2(100) NOT NULL, -- PUBLICATION OF THE BOOK
    QUANTITY      NUMBER(5) NOT NULL, -- QUANTITY OF THE BOOK ORDERED
    S_ID          CHAR(10) NOT NULL, -- SELLER ID OF THE BOOK ORDERED
    ORD_DATE      DATE DEFAULT SYSDATE, -- ORDER DATE OF THE BOOK
    CONSTRAINT BK_ORD_PK PRIMARY KEY (ORD_ID, BK_TTL), -- PRIMARY KEY CONSTRAINT ON ORDER ID AND BOOK TITLE
    CONSTRAINT FK_ORDER_SELLER FOREIGN KEY (S_ID) REFERENCES TBL_SELLER(S_ID) -- FOREIGN KEY CONSTRAINT ON SELLER ID
);

-- BILL TABLE WHERE THE DETAILS OF THE BILLS ARE STORED. THIS TABLE IS USED TO STORE THE DETAILS OF THE BILLS GENERATED FOR THE BOOKS PURCHASED FROM THE SELLERS.

CREATE TABLE TBL_BILL (
    B_ID      CHAR(10), -- BILL ID OF THE BOOK
    S_ID      CHAR(10) NOT NULL, -- SELLER ID OF THE BOOK
    TTL       VARCHAR2(100) NOT NULL, -- TITLE OF THE BOOK
    AUTHOR    VARCHAR2(100) NOT NULL, -- AUTHOR OF THE BOOK
    QUANTITY  NUMBER(5) NOT NULL, -- QUANTITY OF THE BOOK
    U_PRICE   NUMBER(5,2) NOT NULL, -- UNIT PRICE OF THE BOOK
    B_DATE    DATE DEFAULT SYSDATE, -- BILL DATE OF THE BOOK
    TAX       NUMBER(5) NOT NULL, -- TAX ON THE BOOK
    TTL_AMUT  NUMBER(10) NOT NULL, -- TOTAL AMOUNT OF THE BILL
    GR_TTL    NUMBER(10) NOT NULL, -- GRAND TOTAL OF THE BILL
    CONSTRAINT BILL_PK PRIMARY KEY (B_ID, TTL), -- PRIMARY KEY CONSTRAINT ON BILL ID AND TITLE
    CONSTRAINT FK_BILL_SELLER FOREIGN KEY (S_ID) REFERENCES TBL_SELLER(S_ID) -- FOREIGN KEY CONSTRAINT ON SELLER ID
);



--CIRCULATION MODULE

-- CIRCULATION TABLE WHERE THE DETAILS OF THE CIRCULATION ARE STORED.

CREATE TABLE TBL_CIRCULATION (
    ISS_ID       NUMBER(10) CONSTRAINT CIRC_PK PRIMARY KEY, -- ISSUE ID OF THE BOOK
    CARD_ID      CHAR(9) NOT NULL, -- LIBRARY CARD ID OF THE STUDENT WHO ISSUED THE BOOK
    ACCESS_NO    CHAR(4) NOT NULL, -- ACCESSION NUMBER OF THE BOOK ISSUED
    ISSU_DATE    DATE DEFAULT SYSDATE, -- ISSUE DATE OF THE BOOK
    DUE_DATE     DATE NOT NULL, -- DUE DATE FOR RETURNING THE BOOK
    RTR_DATE     DATE, -- RETURN DATE OF THE BOOK
    FINE_AMT     NUMBER(6,2), -- FINE AMOUNT FOR LATE RETURN OF THE BOOK
    CONSTRAINT FK_CIRC_STUDENT FOREIGN KEY (CARD_ID) REFERENCES TBL_STUDENT(CARD_ID), -- FOREIGN KEY CONSTRAINT ON LIBRARY CARD ID
    CONSTRAINT FK_CIRC_BOOK FOREIGN KEY (ACCESS_NO) REFERENCES TBL_BOOK_INFORMATION(ACCESS_NO) -- FOREIGN KEY CONSTRAINT ON ACCESSION NUMBER

);

INSERT INTO TBL_CREDENTIALS VALUES('ADMIN','ADMINISTRATOR','ADMIN','zaynrex5@gmail.com','1234567890');

SELECT * FROM TBL_CREDENTIALS;

COMMIT;
