DROP USER PRJ2531H CASCADE;
CREATE USER PRJ2531H IDENTIFIED BY PRJ2531H;
GRANT CONNECT, RESOURCE TO PRJ2531H;
GRANT DBA TO PRJ2531H;
GRANT UNLIMITED TABLESPACE TO PRJ2531H;
CONNECT PRJ2531H/PRJ2531H;




CREATE TABLE TBL_CREDENTIALS (
    USER_ID   CHAR(5) CONSTRAINT LOGIN_PK PRIMARY KEY, 
    NAME      VARCHAR2(20) NOT NULL,
    PASSWORD  VARCHAR2(10) NOT NULL,
    SQUES     VARCHAR2(50) NOT NULL,    
    SANS      VARCHAR2(50) NOT NULL
);

CREATE TABLE TBL_SELLER (
    S_ID       CHAR(10) CONSTRAINT SEL_PK PRIMARY KEY,
    COMP_NAME  VARCHAR2(30) NOT NULL,
    S_PH_NUMB  NUMBER(10) NOT NULL,
    S_EMAIL    VARCHAR2(50) NOT NULL,
    CONT_PRSN  VARCHAR2(30),
    PH_NUMB    NUMBER (10) NOT NULL,   
    EMAIL      VARCHAR2(50),
    ADDR       VARCHAR2(100) NOT NULL
);

CREATE TABLE TBL_AUTHOR (
    A_ID    CHAR(10) CONSTRAINT AUT_PK PRIMARY KEY,
    A_NAME  VARCHAR2(100) NOT NULL
);

CREATE TABLE TBL_PUBLISHER (
    P_ID    CHAR(10) CONSTRAINT PUB_PK PRIMARY KEY,
    P_NAME  VARCHAR2(100) NOT NULL
);


CREATE TABLE TBL_BOOK_INFORMATION (
    ACCESS_NO   CHAR(4) CONSTRAINT BK_INFO_PK PRIMARY KEY,
    BK_TITLE    VARCHAR2(100) UNIQUE NOT NULL,
    EDITION     NUMBER(10),
    SOURCE      VARCHAR2(10),
    QUANTITY    NUMBER(5) NOT NULL,
    PAGES       NUMBER(5) NOT NULL,
    ENTRY_DATE  DATE NOT NULL,
    AUTHOR_NAME VARCHAR2(50) NOT NULL,
    A_ID        CHAR(10) NOT NULL,
    P_ID        CHAR(10) NOT NULL,
    VOLUME      NUMBER(5),
    U_PRICE     NUMBER(6,2) NOT NULL,
    PUB_YEAR    NUMBER(4) NOT NULL,
    B_NO        NUMBER(5),
    B_DATE      DATE NOT NULL,
    REMARKS     VARCHAR2(50),           
    CONSTRAINT FK_BOOK_PUB FOREIGN KEY (P_ID) REFERENCES TBL_PUBLISHER(P_ID),
    CONSTRAINT FK_BOOK_AUT FOREIGN KEY (A_ID) REFERENCES TBL_AUTHOR(A_ID)
);

CREATE TABLE TBL_BOOK_ORDER (
    ORD_ID        CHAR(10),
    BK_TTL        VARCHAR2(100) NOT NULL,
    AUTHOR        VARCHAR2(100) NOT NULL,
    PUBLICATION   VARCHAR2(100) NOT NULL,
    QUANTITY      NUMBER(5) NOT NULL,
    S_ID          CHAR(10) NOT NULL,
    ORD_DATE      DATE DEFAULT SYSDATE,
    CONSTRAINT BK_ORD_PK PRIMARY KEY (ORD_ID, BK_TTL),
    CONSTRAINT FK_ORDER_SELLER FOREIGN KEY (S_ID) REFERENCES TBL_SELLER(S_ID)
);

CREATE TABLE TBL_BILL (
    B_ID      CHAR(10),
    S_ID      CHAR(10) NOT NULL,
    TTL       VARCHAR2(100) NOT NULL,
    AUTHOR    VARCHAR2(100) NOT NULL,
    QUANTITY  NUMBER(5) NOT NULL,
    U_PRICE   NUMBER(5,2) NOT NULL,
    B_DATE    DATE DEFAULT SYSDATE,
    TAX       NUMBER(5) NOT NULL,
    TTL_AMUT  NUMBER(10) NOT NULL,
    GR_TTL    NUMBER(10) NOT NULL,
    CONSTRAINT BILL_PK PRIMARY KEY (B_ID, TTL),
    CONSTRAINT FK_BILL_SELLER FOREIGN KEY (S_ID) REFERENCES TBL_SELLER(S_ID)
);

CREATE TABLE TBL_BOOK_STOCK (
    ACCESS_NO   CHAR(4) CONSTRAINT BK_STOCK_PK PRIMARY KEY,
    BK_TITLE    VARCHAR2(100) NOT NULL,
    P_LOCATION  VARCHAR2(50) NOT NULL,
    QUANTITY    NUMBER(5) NOT NULL,
    REMARKS     VARCHAR2(50),
    CONSTRAINT FK_STOCK_BOOK FOREIGN KEY (BK_TITLE) REFERENCES TBL_BOOK_INFORMATION (BK_TITLE)
);

CREATE TABLE TBL_STUDENT (
    CARD_ID   CHAR(9) CONSTRAINT STUD_PK PRIMARY KEY,
    ROLL      NUMBER(5) NOT NULL UNIQUE,
    NAME      VARCHAR2(50) NOT NULL,
    PH_NO     NUMBER(10) NOT NULL,   
    ADDR      VARCHAR2(100) NOT NULL,
    COURSE    CHAR(3) NOT NULL,
    ACAD_SESSION   CHAR(9) NOT NULL,
    RECEIPT_NO VARCHAR(10) NOT NULL UNIQUE,
    ISSUED_BY VARCHAR2(20) NOT NULL,
    ISSUE_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOOK_LIMIT NUMBER(1) DEFAULT 1 NOT NULL,
    FEE  NUMBER(5,2) NOT NULL,
    STATUS VARCHAR2(9) NOT NULL
);

CREATE TABLE TBL_CIRCULATION (
    ISS_ID       NUMBER(10) CONSTRAINT CIRC_PK PRIMARY KEY,
    CARD_ID      CHAR(9) NOT NULL,
    ACCESS_NO    CHAR(4) NOT NULL,
    ISSU_DATE    DATE DEFAULT SYSDATE,
    DUE_DATE     DATE NOT NULL,
    RTR_DATE     DATE,
    FINE_AMT     NUMBER(6,2),
    CONSTRAINT FK_CIRC_STUDENT FOREIGN KEY (CARD_ID) REFERENCES TBL_STUDENT(CARD_ID),
    CONSTRAINT FK_CIRC_BOOK FOREIGN KEY (ACCESS_NO) REFERENCES TBL_BOOK_INFORMATION(ACCESS_NO) 
);

INSERT INTO TBL_CREDENTIALS VALUES('LIB01','LIBRARIAN','LIB01','WHAT APPLICATION IS THIS','LMS');

SELECT * FROM TBL_CREDENTIALS;